dist: trusty
language: generic

env:
  global:
    ENCRYPTION_LABEL: "b9b018a1d67d"

addons:
  ssh_known_hosts: console.spec.whatwg.org

script:
- bash ./deploy.sh

notifications:
  email:
    on_success: never
    on_failure: always
