dist: trusty
language: generic

env:
  global:
    - ENCRYPTION_LABEL="b9b018a1d67d"
    - DEPLOY_USER="ddenicola"

script:
  - make deploy

notifications:
  email:
    on_success: never
    on_failure: always
